### ISSUE TITLE
Add sharp

### ISSUE THREAD

**Issue by wmertens** [ivanoff/image-processing-compare#1]
http://sharp.dimens.io/en/stable/ claims to be super fast, and I'm curious if that is indeed the case :)

**Comment by ivanoff** [comment]
Thanks!
Sharp beats them all! :)
:+1: 

> sharp.js : 8.451 img/sec
> canvas.js : 5.561 img/sec
> gm.js : 2.359 img/sec
> gm-imagemagic.js : 1.633 img/sec
> lwip.js : 0.821 img/sec
